### PR TITLE
add option to ignore empty modifier

### PR DESCRIPTION
**Pull request by CrazyToken**
Hi pierre3,
thanks for providing this amazing library.
I need some additions, one of it is this pull request, which provides the ability to ignore Properties without accessibility modifier.
I actually planned to implement it within the existing -ignore attribute, but discarded it.
For some examples see the included unit test.
I plan in some additional pull requests:

- add attribute to add "noters" to single attributes
- add attribute to add a class to a "collection". Via plantuml skins those classes/collections can then get equal background-colors
- add include_"collection".puml  to have the possibility to have "data-groups" / "data-categories".

Best wishes
Maik

### CODE REVIEW

**Comment by CrazyToken** [comment]
Hi @pierre3,
any feedback for this PR? Would you mind merging it?
Greetings
Maik

**Comment by CrazyToken** [comment]
Hi @pierre3,
added another commit which gives the opportunity to exclude the @startuml and @enduml tags from the exported puml files.
This is usefull if you want to merge a sub-collection of classes into one diagramm.
Asciidoc otherwise truncates the diagramm convertion at the first @enduml of the first file.
Please Review, merge and create a new version :-)
Greetings Maik

**Comment by pierre3** [comment]
Hi @CrazyToken 

I apologize for the delay in confirmation. Thank you for the pull request!
I didn't consider the behavior when access modifiers were omitted.
I'm thinking of treating it the same as "private" in accordance with the C# specification, what do you think?
(If you want to ignore members with omitted access modifiers, you can specify "private".)

csharp
```cs
class A
{
     + A : int <<get>>
    B : int <<get>>
    + MethodA() : void
    MethodB() : void
}
```

PlantUml
```
class A{
    + A : int <<get>>
    - B : int <<get>>
    + MethodA() : void
    - MethodB() : void
}
```

**Comment by CrazyToken** [comment]
Hi @pierre3,
great Idea, as this prevents the project from having one more config option and thus more complexity.
Currently I do not have the time to make the changes by myself. Maybe someone else is also interested in this Topic.
Best wishes
Maik

**Comment by pierre3** [comment]
I have merged the following commit:
"exclude the @startuml and @enduml tags"
6f7677c5457d6a3944c0dfc2c10ae7bdc85349c4 , 0167511b1768deea60ef2f910f3ffd703fc4883e

**Comment by pierre3** [comment]
@CrazyToken,
I have released version 1.3.2, and I would like to express my gratitude for your  contribution.

- NuGet:  https://www.nuget.org/packages/PlantUmlClassDiagramGenerator/1.3.2#release-body-tab
- VSCode Extension: https://marketplace.visualstudio.com/items?itemName=pierre3.csharp-to-plantuml

**Pull request closed without merging**
