### PR TITLE
fix: fix associations (nullable, Associated types, etc.) 

### LINKED ISSUE #83: Only nullable properties are outputted
Having the following C# code:

```
public class Test
{
    public LinkedClass AdditionalData { get; set; }
    public LinkedClass? AdditionalData2 { get; set; }
}

public class LinkedClass
{
    public string Name { get; set; }
}
```

and running the following command: `dotnet puml-gen ./ ./UML -dir -public -createAssociation`

I get the following output:

```
@startuml
class Test {
    + AdditionalData2 : LinkedClass? <<get>> <<set>>
}
class LinkedClass {
    + Name : string <<get>> <<set>>
}
Test --> "AdditionalData" LinkedClass
@enduml
```

Only the nullable property is outputted.
Using version 1.3.4

### PR DESCRIPTION
**Pull request by PendingChanges**
FIxes #83 #37 #11

### CODE REVIEW

**Comment by pierre3** [comment]
Regarding the fixes for #37 and #11.

If the type of the member is a collection, this works fine, but if it's not a collection, it changes the meaning and is not convenient.

```cs
class item
{
    public string Name { get; set; }
}
class classA
{
    //collection type
    public IList<item> Items { get; set; }
}
```
image

```cs
class ArgType
{
}
class Item<T>
{
    public T Value { get; set; }
}

class classB
{
    //non-collection type
    public Item<ArgType> Item { get; set; }
}
```

image

The related type is not `ArgType` but rather `Item<ArgType>`, so the meaning changes.

**Comment by pierre3** [comment]
In the current implementation, there isn't a clear way to determine whether the type of a property or field is a collection. It would be helpful to have a good solution if available.

**Comment by pierre3** [comment]
@PendingChanges 
Could you please create a separate Pull Request for #83? It would be helpful if you could create Pull Requests for each feature if possible.

**Comment by Remi-Aubert** [comment]
> @PendingChanges Could you please create a separate Pull Request for #83? It would be helpful if you could create Pull Requests for each feature if possible.

Yes your're right!

**Comment by Remi-Aubert** [comment]
> In the current implementation, there isn't a clear way to determine whether the type of a property or field is a collection. It would be helpful to have a good solution if available.

I went into this issue while fixing it, will look at it again.

**Comment by pierre3** [comment]
I think it's good. think that's the best way to approach it given the current situation.

**Pull request closed without merging**
